### DISCUSSION TITLE
Custom dotenv each recipe

### DISCUSSION THREAD

**Discussion by 8thgencore** [casey/just#2475] [Q&A]
How can dotenv-filename or dotenv-path be defined for each recipe in the justfile configuration?

example:
```yaml
[group('docker')]
docker-build-dev:
  # TODO: set dotenv-filename := ".env.dev"
  docker compose up -d

[group('docker')]
docker-deploy-prod:
  # TODO: set dotenv-filename := ".env"
  docker compose up -d

```
