### ISSUE TITLE
justfile + pre-commit-config.yaml interaction -- just treating staged files as recipe names

### ISSUE THREAD

**Issue by alexander-xerxes-grant** [casey/just#1435]
#pre-commit-config.yaml

```
repos:
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: just flake8
        language: system
        types_or: [python, flake8]
```
        
#justfile

```
flake8:
		poetry run flake8
```
		
When running `pre-commit run flake8` the output is:

```
pre-commit run flake8
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

error: Justfile does not contain recipe `src/application/hello_world.py`.
```

The expected behavior is for just to parse the file path of the staged file as an argument to be passed to flake8, not as a separate recipe.

I have moved from using this setup with a Makefile and so I'm sure I've missed something in the docs about passing arguments to recipes, but any help would be greatly appreciated.
