### ISSUE TITLE
Some dependencies out of date

### ISSUE THREAD

**Issue by chrisvittal** [casey/just#224]
The following entries in `Cargo.toml` are out of date and can be updated.

```toml
edit-distance = "^2.0.0"
itertools     = "^0.6.0"
regex         = "^0.2.0"
```

Updating regex causes breakage as the `at` method on `Captures` has been removed. The equivalent to `captures.at(n).unwrap()` seems to be `captures.get(n).unwrap().as_str()`.

I have a branch where I've done the work, it can be seen [here](https://github.com/chrisvittal/just/commit/65af008d066cfbf8f5953f63bcd5d3b2a269f701). Let me know if you would like a pull request for this issue.
